spring:
  application:
    name: Configuration server

server:
  servlet:
    context-path: /config
  port: 9001

logging:
  level:
    root: INFO
    com.myapp.demo: DEBUG
  file:
    name: ./logs/config-server.log